Feature/virtualizer new approach
robotology/walking-teleoperation pull request #61
Opened 2021-06-17 16:03 UTC by GiulioRomualdi

This PR is still in draft and before merging it we should clean a bit the code and improve the performances on iCub

This PR is only to keep track of the activity.  This code runs in icub-virtualizer laptop

2021-07-01 07:01 UTC, GiulioRomualdi commented
I cleaned the history and I also removed hardcoded 5 for the walking linear velocity.

The PR is ready to be reviewed @S-Dafarra and @kouroshD

2021-07-01 08:41 UTC, S-Dafarra approved these changes
LGTM. Just to understand, the connection of the goal port to the walking controller needs to be done manually, right?

2021-07-06 07:35 UTC, GiulioRomualdi commented
Yes as before. In theory, this should be done by the application.

2021-07-08 15:32 UTC, kouroshD requested changes
Thank you @GiulioRomualdi  for the PR. I have added some minor comments.

2021-07-08 15:32 UTC, kouroshD commented on app/robots/iCubGenova09/virtualizerConfig.ini
> +rpcWalkingPort_name           /goal:o
Please update the `rpcWalkingPort_name` with some name like `robotGoalPort_name` or sth similar.

2021-07-08 15:32 UTC, kouroshD commented on app/robots/iCubGenova09/virtualizerConfig.ini
> +rpcWalkingPort_name           /goal:o
Please update the port name in all the xml files.

2021-07-08 15:32 UTC, kouroshD commented on app/robots/iCubGenova09/virtualizerConfig.ini
> +rpcWalkingPort_name           /goal:o
Also, please also put the same port name for all the robot in the `.ini` files.
Thanks :)

2021-07-13 13:30 UTC, kouroshD requested changes

2021-07-13 13:30 UTC, kouroshD commented on app/robots/iCubGenova09/virtualizerConfig.ini
> +rpcWalkingPort_name           /goal:o
```suggestion
goalWalkingPort_name           /goal:o
```

2021-07-13 13:30 UTC, kouroshD commented on modules/Virtualizer_module/src/VirtualizerModule.cpp
>      if (!YarpHelper::getStringFromSearchable(rf, "rpcWalkingPort_name", portName))
```suggestion
    if (!YarpHelper::getStringFromSearchable(rf, "goalWalkingPort_name", portName))
```

2021-07-13 13:33 UTC, kouroshD commented
@GiulioRomualdi  let me know if there are some updates on this?

2021-07-22 09:03 UTC, kouroshD commented
@GiulioRomualdi  As I wrote you before, I have updated the configuration files; I rebased it also on top of devel :) .
Let me know if it is OK for you, so we can merge it.

2021-07-22 09:04 UTC, kouroshD approved these changes

2021-07-22 16:04 UTC, GiulioRomualdi commented
> @GiulioRomualdi As I wrote you before, I have updated the configuration files; I rebased it also on top of devel :) .
> Please have a look as well, and let me know if it is OK for you, so we can merge it.

It's ok! You can merge it. Thank you @kouroshD

2021-07-23 17:03 UTC, merged